### ISSUE TITLE
Refactor MainLayout.js

### ISSUE THREAD

**Issue by MaksymTaratuta55** [ramsayinnovations/ramsay-site#45]
MainLayout.js is better to be

`<div className="wrapper">
       		<Header />
    		<main>
			{children}
		</main>
    		<Footer />
      </div>`

**Comment by thecodeclimber** [comment]
@kirti75waytech 

Please rewrite the code in `components/main/index.js` as follows:

```
const MainLayout = ({ children }) => (
  <div>
    <Header />
    <main>
    {children}
    </main>
    <Footer />
  </div>
);
```

NOTE:

* We have REMOVED the `<Base>` component (as noted in another issue).
* We have REPLACED `<Base>` with a `<div>` tag
* We have NOT added any classes to the `<div>` tag
* We have wrapped `{children}` in a `<main>` tag

@MaksymTaratuta55 Note:  for now I do not want to add `className="wrapper"` to the `<div>` tag since we are using `tailwind css` and in general do not need (or even want) to add custom class names unless we have no choice (which should be rare).  These two articles are a good introduction to the main concept of tailwind css:

* https://tailwindcss.com/docs/utility-first
* https://tailwindcss.com/docs/extracting-components

**Comment by MaksymTaratuta55** [comment]
@thecodeclimber, git it. It was just an example

**Comment by kirti75waytech** [comment]
@thecodeclimber Changes have been done. Please review this and let me know If changes are required. Thanks

**Comment by thecodeclimber** [comment]
@kirti75waytech -- I decided to move the base `<div>` tag and just use a React fragment -- like this:

```
  <>
    <Header />
    <main>
      {children}
    </main>
    <Footer />
  </>
``

**Comment by kirti75waytech** [comment]
@thecodeclimber Noted this.
